// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNbOi-C2QsZIa9H6XTzQw62BNVNx5_nkQ',
    appId: '1:926599368373:web:d74047addb20379f6fb8fc',
    messagingSenderId: '926599368373',
    projectId: 'golf-league-b0bb2',
    authDomain: 'golf-league-b0bb2.firebaseapp.com',
    storageBucket: 'golf-league-b0bb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdY2zvezLb0S3sdEBIbeG2VJZydcaF3rM',
    appId: '1:926599368373:android:c777f4a9d09b6b736fb8fc',
    messagingSenderId: '926599368373',
    projectId: 'golf-league-b0bb2',
    storageBucket: 'golf-league-b0bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.goldenoaks.golf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.goldenoaks.golf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNbOi-C2QsZIa9H6XTzQw62BNVNx5_nkQ',
    appId: '1:926599368373:web:d74047addb20379f6fb8fc',
    messagingSenderId: '926599368373',
    projectId: 'golf-league-b0bb2',
    authDomain: 'golf-league-b0bb2.firebaseapp.com',
    storageBucket: 'golf-league-b0bb2.firebasestorage.app',
  );
}